# Generated by Django 5.0 on 2024-04-21 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_staffmanagement'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoteldetails',
            name='deluxeprice',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='hoteldetails',
            name='standardprice',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='hoteldetails',
            name='suiteprice',
            field=models.IntegerField(default=150),
        ),
    ]
