# Generated by Django 5.0 on 2024-04-26 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbookings',
            name='Hotelname',
            field=models.CharField(default='koya', max_length=255),
        ),
    ]
